import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Session } from "inspector/promises"
import App from "@/app/App"
import { Providers } from "./providers"
import { Suspense } from "react"
import Loading from "@/components/ui/Loading"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  session?: Session | null
}>) {
  return (
    <html lang="vi">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<Loading />}>
          <Providers>
            <App>{children}</App>
          </Providers>
        </Suspense>
      </body>
    </html>
  )
}
